version: '3'

# volumes:
#   prometheus_data:
#     external: true
  # grafana_data:
  #   external: true

services:
  grafana:
    image: grafana/grafana:12.0.2
    container_name: grafana
    depends_on:
      - influxdb
    user: root
    environment:
      GF_SECURITY_ADMIN_USER: ${USER}
      GF_SECURITY_ADMIN_PASSWORD: ${PASSWORD}
      GF_PATHS_PROVISIONG: /etc/grafana/provisioning
    ports:
      - 3000:3000
    volumes:
      - ./grafana/data:/var/lib/grafana
    networks:
      - monitoring

  influxdb:
    image: influxdb:2.1.1
    container_name: influxdb
    restart: always
    volumes:
      # Mount for influxdb data directory and configuration
      - ./influxdb2:/var/lib/influxdb2:rw
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${_INFLUXDB_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${_INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${_INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${BUCKET_NAME}
      - DOCKER_INFLUXDB_INIT_RETENTION=30d
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${_INFLUXDB_TOKEN}
    networks:
      - monitoring

networks:
  monitoring:
    external: true
