apiVersion: v1
kind: Service
metadata:
  name: telegraf-ds
spec:
  selector:
    app.kubernetes.io/name: telegraf-ds
  ports:
    - name: statsd
      protocol: UDP
      port: 9125
      targetPort: 9125
  type: ClusterIP
